controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#index: TODO: remove if you decide for annotations
#    path: /
#    controller: 'App\Controller\TestController::index'