version: '3.8'

services:

  #php
  app:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    container_name: sudokuSR-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www

  #web server
  nginx:
    image: nginx:1.19-alpine
    container_name: sudokuSR-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ../.docker/.nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ../.docker/.nginx/conf.d:/etc/nginx/conf.d